input {
  jdbc {
    jdbc_driver_library => "/home/devpedro/.m2/repository/org/postgresql/postgresql/42.7.11/postgresql-42.7.11.jar"
    jdbc_driver_class => "org.postgresql.Driver"

    jdbc_connection_string => "jdbc:postgresql://localhost:5432/logdb"
    jdbc_user => "postgres"
    jdbc_password => "ph12345"

    statement => "SELECT * FROM logs WHERE id > :sql_last_value"

    use_column_value => true
    tracking_column => "id"

    last_run_metadata_path => "/home/devpedro/Documentos/faculdade/projetos/periodo4/bancoDeDados2/nota2/LogVision/logstash/.last_run"

    clean_run => false

    schedule => "*/10 * * * * *"
  }
}
output {
  stdout {
    codec => rubydebug
  }
}