input {
  jdbc {
    jdbc_driver_library => "/caminho/postgresql.jar"
    jdbc_driver_class => "org.postgresql.Driver"

    jdbc_connection_string => "jdbc:postgresql://localhost:5432/logdb"
    jdbc_user => "${DB_USER}"
    jdbc_password => "${DB_PASSWORD}"

    statement => "SELECT * FROM logs"

    schedule => "* * * * *"
  }
}

filter {

  if [message] =~ /Senha inválida/ {
    mutate {
      add_field => { "category" => "authentication_error" }
    }
  }

  if [message] =~ /Falha ao conectar ao banco/ {
    mutate {
      add_field => { "category" => "database_error" }
    }
  }

  if [message] =~ /Timeout/ {
    mutate {
      add_field => { "category" => "network_error" }
    }
  }

}

output {
  stdout {
    codec => rubydebug
  }
}